<?php
// Se incluyen los archivos de configuración global y de la base de datos
require_once '../../../config/global.php';
require_once '../../../config/db.php';

define('RUTA_INCLUDE', '../../../'); // Definir la ruta de inclusión, ajusta según sea necesario

// Conexión a la base de datos
$conn = new mysqli("database-team1-daw.c30w0agw4764.us-east-2.rds.amazonaws.com", "admin", "S1stemas_23", "PP_TEAM1");
if ($conn->connect_error) {
    die("Conexión fallida: " . $conn->connect_error); // Mostrar error si falla la conexión
}

// Obtener datos de la tabla usuarios_alumno
$matricula = '202160171'; // Ajustar según sea necesario
$sql = "SELECT nombre, matricula, semestre, licenciatura FROM usuarios_alumno WHERE matricula = '$matricula'";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // Obtener los datos del primer resultado
    $row = $result->fetch_assoc();
    $nombre = $row['nombre'];
    $matricula = $row['matricula'];
    $semestre = $row['semestre'];
    $licenciatura = $row['licenciatura'];
} else {
    die("No se encontraron datos del alumno."); // Mostrar error si no se encuentran datos
}

$conn->close(); // Cerrar la conexión a la base de datos

// Establecer la zona horaria a Ciudad de México
date_default_timezone_set('America/Mexico_City');
// Definir los nombres de los meses en español
$meses = [
    1 => 'enero', 2 => 'febrero', 3 => 'marzo', 4 => 'abril', 5 => 'mayo', 6 => 'junio',
    7 => 'julio', 8 => 'agosto', 9 => 'septiembre', 10 => 'octubre', 11 => 'noviembre', 12 => 'diciembre'
];

// Obtener la fecha actual en el formato deseado
$fecha_actual = date('d') . ' de ' . $meses[date('n')] . ' de ' . date('Y');

require_once('tcpdf_include.php'); // Incluir la biblioteca TCPDF

// Crear nuevo documento PDF en tamaño carta
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, 'LETTER', true, 'UTF-8', false);

// Información del documento
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Generated by Abimael');
$pdf->SetTitle('Plan de Trabajo de Prácticas Profesionales');
$pdf->SetSubject('Plan de Trabajo');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// Eliminar la cabecera y pie de página predeterminados
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Establecer márgenes
$pdf->SetMargins(15, 20, 15); // Ajustar los márgenes (izquierda, arriba, derecha)

// Establecer salto de página automático
$pdf->SetAutoPageBreak(TRUE, 30); // Ajustar el margen inferior para el salto de página

// Factor de escala de imagen
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Establecer modo de subconfiguración de fuente predeterminado
$pdf->setFontSubsetting(true);

// Establecer fuente
$pdf->SetFont('dejavusans', '', 10, '', true);

// Añadir una página
$pdf->AddPage();

// Definir el contenido HTML con estilo CSS
$html = <<<EOD
<style>
    .title {
        text-align: right;
        font-weight: bold;
        margin-bottom: 5px;
    }
    .subtitle {
        text-align: right;
        font-weight: bold;
        margin-bottom: 5px;
    }
    .content {
        text-align: justify;
        margin-bottom: 5px;
    }
    .signature {
        text-align: center;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 5px;
    }
    th, td {
        border: 1px solid black;
        padding: 5px;
        margin-bottom: 5px;
    }
    .no-border {
        border: none;
    }
    .header-cell {
        background-color: #9b9b9b;
        color: white;
        font-weight: bold;
    }
</style>
<table>
    <tr>
        <td class="no-border">
            <div style="margin-top: 10px;"><img src="unnamed.jpg" width="200" alt="Logo Universidad Cristobal"></div>
        </td>
        
    </tr>
    <tr>
        <td class="no-border title" colspan="2" >Universidad Cristóbal Colón</td>
    </tr>
    
    <tr>
        <td class="no-border subtitle" colspan="2">Licenciatura en Ingeniería en Sistemas Computacionales</td>
    </tr>
    <tr>
        <td class="no-border subtitle" colspan="2">Plan de Trabajo de Prácticas Profesionales</td>
    </tr>
</table>



<table>
    <tr>
        <td class="header-cell">1. Nombre del alumno:</td>
        <td>{$nombre}</td>
        <td class="header-cell">2. Matrícula:</td>
        <td>{$matricula}</td>
    </tr>
    <tr>
        <td class="header-cell">3. Licenciatura:</td>
        <td>{$licenciatura}</td>
        <td class="header-cell">4. Semestre:</td>
        <td>{$semestre}</td>
    </tr>
    <tr>
        <td class="header-cell">5. Nombre de la empresa:</td>
        <td colspan="3"></td>
    </tr>
    <tr>
        <td class="header-cell">6. Fecha de inicio de las prácticas:</td>
        <td colspan="3"> / / </td>
    </tr>
    <tr>
        <td class="header-cell">7. Duración en horas (estimadas):</td>
        <td colspan="3"></td>
    </tr>
    <tr>
        <td class="header-cell">8. Horario:</td>
        <td colspan="3"></td>
    </tr>
    <tr>
        <td class="header-cell">10. Descripción general de las actividades a realizar:</td>
        <td colspan="3">
            <ol>
                <li>ashdfkahsdfklahsdflaksdfhalksdfjhalskfhlaksjdfhalksjdfhalksjdfhalksdhfalksdfhalksdfhalksdfhalksdfhaj.</li>
                <li>.jskdfhalkjdsfhalksdfhalksdjfhalkjsdfhalkjsdfhalksdjfhalkjsdfhalkjdfshaj</li>
                <li></li>
                <li></li>
            </ol>
        </td>
    </tr>
</table>

<p class="content">H. Veracruz, Ver., a {$fecha_actual}</p>

<br><br>

<table>
    <tr>
        <br><br><br><td class="no-border signature">___________________________________<br>$nombre<br>Alumno</td>
        <td class="no-border signature">_____________________________________<br>Nombre y firma del supervisor<br>Supervisor</td>
    </tr>
    <tr>
        <br><br><br><br><td class="no-border signature">_____________________________________<br>Mtro. Ramón Palet Naranjo<br>Vo. Bo. Jefe de Área Académica</td>
        <td class="no-border signature">_____________________________________<br>Mtra. María del Carmen Aguirre Torres<br>Vo. Bo. Aseguramiento de la Calidad</td>
    </tr>
</table>
EOD;

// Imprimir texto usando writeHTMLCell()
$pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);

// Cerrar y generar el documento PDF
$pdf->Output('plan_trabajo_practicas.pdf', 'I');
?>
