<?php
require_once '../../../config/global.php';
require_once '../../../config/db.php';

define('RUTA_INCLUDE', '../../../'); // ajustar a necesidad

// Conexión a la base de datos
$conn = new mysqli("database-team1-daw.c30w0agw4764.us-east-2.rds.amazonaws.com", "admin", "S1stemas_23", "PP_TEAM1");
if ($conn->connect_error) {
die("Conexión fallida: " . $conn->connect_error);
}

// Obtener datos de la tabla usuarios_alumno
$matricula = '202160327';
$sql = "SELECT nombre, matricula, licenciatura, semestre, correo, sexo FROM usuarios_alumno WHERE matricula = '$matricula'"; // Ajusta el WHERE según sea necesario
$result = $conn->query($sql);
if ($result->num_rows > 0) {
// Obtener los datos del primer resultado
$row = $result->fetch_assoc();
$nombre = $row['nombre'];
$matricula = $row['matricula'];
$licenciatura = $row['licenciatura'];
$semestre = $row['semestre'];
$correo = $row['correo'];
$sexo = $row['sexo'];
} else {
die("No se encontraron datos del alumno.");
}

$conn->close();

require_once('tcpdf_include.php');

// Crear nuevo documento PDF en tamaño carta
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, 'LETTER', true, 'UTF-8', false);

// Información del documento
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Generated by TCPDF');
$pdf->SetTitle('Solicitud para realización de Prácticas Profesionales');
$pdf->SetSubject('Solicitud de Prácticas');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// Eliminar la cabecera y pie de página predeterminados
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Establecer márgenes
$pdf->SetMargins(10, 20, 10);

// Establecer salto de página automático
$pdf->SetAutoPageBreak(TRUE, 10);

// Factor de escala de imagen
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Establecer modo de subconfiguración de fuente predeterminado
$pdf->setFontSubsetting(true);

// Establecer fuente
$pdf->SetFont('dejavusans', '', 10, '', true);

// Añadir una página
$pdf->AddPage();

// Contenido HTML
$html = <<<EOD
<style>
    table {
        border-collapse: collapse;
    }
    td, th {
        border: 1px solid black;
        padding: 4px;
    }
    .no-border {
        border: none;
    }
    .center {
        text-align: center;
    }
</style>
<table class="no-border" cellpadding="4">
    <tr>
        <td class="no-border"><img src="path/to/logo.png" height="50"></td>
        <td class="no-border" colspan="2" class="center">
            <h3>Universidad Cristóbal Colón</h3>
            <h4>Licenciatura en Ingeniería en Sistemas Computacionales</h4>
            <h4>Solicitud para realización de Prácticas Profesionales</h4>
        </td>
        <td class="no-border" rowspan="3" style="width: 100px; text-align: center;">
            <br><br>
            <p>Fotografía reciente tamaño infantil</p>
        </td>
    </tr>
</table>

<p style="text-align: justify; font-weight: bold;">
    Mtro. Ramón Palet Naranjo<br>
    Jefe Académico de las Licenciaturas en Ingeniería en Sistemas Computacionales, Ingeniería en Telecomunicaciones y Sistemas Electrónicos, Ingeniería Biónica e Ingeniería Mecatrónica.<br>
    Universidad Cristóbal Colón</p>
<p>Por medio de la presente hago de su conocimiento mi deseo de realizar prácticas profesionales en la empresa que a continuación se detalla. Esto con el fin de fortalecer mi formación académica y vincularme con el medio laboral.</p>

<h4>Datos del alumno</h4>
<table>
    <tr>
        <th>1. Nombre:</th>
        <td>{$nombre}</td>
        <th>2. Matrícula:</th>
        <td>{$matricula}</td>
    </tr>
    <tr>
        <th>3. Licenciatura:</th>
        <td>{$licenciatura}</td>
        <th>4. Semestre:</th>
        <td>{$semestre}</td>
    </tr>
    <tr>
        <th>5. E-mail:</th>
        <td>{$correo}</td>
        <th>6. Sexo:</th>
        <td>{$sexo}</td>
    </tr>
</table>

<h4>Datos de la empresa</h4>
<table>
    <tr>
        <th>1. Nombre o razón social:</th>
        <td colspan="3">Compañía de Agua del Municipio de Boca del Río SAPI de CV</td>
    </tr>
    <tr>
        <th>2. Domicilio:</th>
        <td colspan="3">Calz. Juan Pablo II 1600 Fraccionamiento Galaxia, Boca del Río, Veracruz CP 94294</td>
    </tr>
    <tr>
        <th>3. Teléfono:</th>
        <td>(229)-986-2052</td>
        <th>4. E-mail:</th>
        <td>rmartinez@grupomasagua.com</td>
    </tr>
    <tr>
        <th>5. Duración de las prácticas:</th>
        <td colspan="3">240 horas - 3 meses</td>
    </tr>
    <tr>
        <th>6. Puesto tentativo a desempeñar:</th>
        <td>Practicante</td>
        <th>7. Departamento:</th>
        <td>Tecnologías de la Información</td>
    </tr>
    <tr>
        <th>8. Nombre del supervisor directo:</th>
        <td>Guillermo Gómez Fernández</td>
        <th>9. Puesto del supervisor directo:</th>
        <td>Auxiliar TIC</td>
    </tr>
</table>

<p style="text-align: justify;">
    Doy fe de los datos anteriores son fidedignos y me comprometo a cumplir con los lineamientos establecidos por la empresa, así como por el reglamento general de alumnos de la Universidad Cristóbal Colón.
</p>
<p style="text-align: right;">H. Veracruz, Ver., a 9 de abril de 2024</p>
<br><br>
<table><br><br><br><br>
    <tr>
        <td class="no-border center" style="width: 50%; padding-top: 20px;">
            _______________________________<br>
            {$nombre}<br>
            Alumno<br><br><br>
        </td>
        <td class="no-border center" style="width: 50%; padding-top: 20px;">
            _______________________________<br>
            Ing. Guillermo Gómez Fernández<br>
            Supervisor
        </td>
    </tr>
    <tr>
        <td class="no-border center" style="width: 50%; padding-top: 20px;">
            _______________________________<br>
            Mtro. Ramón Palet Naranjo<br>
            Vo. Bo. Jefe de Área Académica
        </td>
        <td class="no-border center" style="width: 50%; padding-top: 20px;">
            _______________________________<br>
            Mtra. María del Carmen Aguirre Torres<br>
            Vo. Bo. Aseguramiento de la Calidad
        </td>
    </tr>
</table>

EOD;

// Imprimir el contenido usando writeHTMLCell()
$pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);

// ---------------------------------------------------------

// Agregar información de contacto al final del PDF
$footerHtml = <<<EOD
<style>
    .footer-table {
        width: 100%;
    }
    .footer-left {
        text-align: left;
        font-size: 8px;
    }
    .footer-right {
        text-align: right;
        font-size: 8px;
    }
</style>
EOD;

// Añadir la información de contacto en el pie de página
$pdf->writeHTMLCell(0, 0, '', '', $footerHtml, 0, 1, 0, true, 'L', true);

// Cerrar y generar el documento PDF
$pdf->Output('solicitud_practicas.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+
?>
